config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root 'home#index'
    get 'shopping',           to: 'shopping#index'
    get 'edit_cart',          to: 'shopping#edit_cart'
    get 'term',               to: 'home#term'
    get 'about_us',           to: 'home#about_us'
    get 'contact',            to: 'home#contact'
    get 'my_acc',             to: 'home#my_acc'
    get 'cart',               to: 'home#cart'
    get 'checkout',           to: 'home#checkout'
    get 'product_detail/:id', to: 'home#product_detail'


    get 'payment',            to: 'payment#index'
    post 'payment',           to: 'payment#create'


    get 'sitemap',            to: 'sitemap#index'

    post 'shopping',          to: 'shopping#cart'
    post 'order',             to: 'home#order'
    post 'information',       to: 'home#information'


    devise_for :customers, controllers: {
      sessions: 'customers/auths/sessions',
      registrations: 'customers/auths/registrations',
      confirmations: 'customers/auths/confirmations',
      passwords: 'customers/auths/passwords'
    }

    devise_for :administrators, controllers: {
      sessions: 'admins/auths/sessions',
      passwords: 'admins/auths/passwords'
    }
  end

  scope "(:locale)", locale: /en/, defaults: {locale: "en"} do
    devise_scope :administrator do
      get 'admin', to: 'admins/auths/sessions#new'
      get 'customers_export', to: 'admins/exports#customers_export'
      get 'admins_export', to: 'admins/exports#admins_export'
      get 'orders_export', to: 'admins/exports#orders_export'
    end

    namespace :admins, path: 'admin' do
      resources :admins
      resources :customers
      resources :products
      resources :photos
      resources :orders
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/shopping_controller.rb
class ShoppingController < ApplicationController
  include Pagy::Backend
  layout 'application'
  def index
    @pagy, @products = pagy(Product.all.order(id: :asc), items: 9, link_extra: 'data-remote="true"')
    if params[:search]
      @pagy, @products = pagy(Product.all.where('name ILIKE ?', "%#{params[:search]}%"))
    elsif params[:city]
      @pagy, @products = pagy(Product.all.where(city_id: params[:city]), items: 9, link_extra: 'data-remote="true"')
    elsif params[:region]
      cities = City.all.where(region_id: params[:region])
      @pagy, @products = pagy(Product.all.where(city_id: cities), items: 9, link_extra: 'data-remote="true"')
    elsif params[:sort]
      @pagy, @products = pagy(Sort.new(Product.all).sort(params[:sort]), items: 9, link_extra: 'data-remote="true"')
      @class_sort = params[:sort]
      respond_to do |format|
        format.js
      end
    elsif params[:sort_contra]
      @pagy, @products = pagy(Sort.new(Product.all).sort_contra(params[:sort_contra]), items: 9, link_extra: 'data-remote="true"')
      @class_sort_contra = params[:sort_contra]
      respond_to do |format|
        format.js
      end
    end
  end

  def cart
    session[:cart] ||= []
    new_cart = [id: params[:item_id], quantity: params[:quantity]]
    if session[:cart].empty?
      tmp = session[:cart].push(new_cart)
      session[:cart]= tmp
    else
      # check trung
      session[:cart].each do |cart|
        if cart[0]["id"] == params[:item_id]
          return cart[0]["quantity"] = params[:quantity].to_i + cart[0]["quantity"].to_i
        end
      end
      tmp = session[:cart].push(new_cart)
      session[:cart]= tmp
    end
  end

  def edit_cart
    if params[:action_edit]=='minus'
      session[:cart].each do |cart|
        if cart[0]["id"] == params[:item_id]
          cart[0]["quantity"] = cart[0]["quantity"].to_i - 1
        end
      end
    elsif params[:action_edit]=='plus'
      session[:cart].each do |cart|
        if cart[0]["id"] == params[:item_id]
          cart[0]["quantity"] = cart[0]["quantity"].to_i + 1
        end
      end
    else
      session[:cart].each do |cart|
        if cart[0]["id"] == params[:item_id]
          cart[0]["quantity"] = 0
        end
      end
    end
    respond_to do |format|
      format.js
    end
  end
end

app/helpers/shopping_helper.rb
module ShoppingHelper
  include Pagy::Frontend
end

app/views/shopping/_edit_cart.html.erb
<div class="row" id="cart">
  <div class="col-xl-9 mb-4">
    <table class="table">
      <thead>
        <tr>
          <th class="text-center">Sản phẩm</th>
          <th class="text-center" style="width: 100px"></th>
          <th class="text-center">Giá</th>
          <th class="text-center" style="width: 225px">Số lượng</th>
          <th>Tổng</th>
          <th> </th>
        </tr>
      </thead>
      <tbody>
        <% session[:cart].each do |cart| %>
          <% product = Product.find(cart[0]["id"]) %>
          <% if cart[0]["quantity"] != 0 %>
            <tr>
              <td class="position-relative text-center">
                <div class="cart-detail"><%= product.name %></div>
              </td>
              <td class="product-thumbnail text-center">
                <%= link_to "product_detail/#{product.id}", class: 'w-100 p-10px' do %>
                  <%= cl_image_tag product.photos.first.photo_url, style:"width: 100px", secure: true %>
                <% end %>
              </td>
              <td class="position-relative text-center">
                <div class="cart-detail" style="width:80px"><%= number_with_delimiter(discount(product)) %> vnd</div>
              </td>
              <td class="product-quantity position-relative" data-title="Quantity">
                <div class="add-to-cart" style="    position: absolute; top: 50%; transform: translateY(-50%);">
                  <%= link_to edit_cart_path(action_edit: "minus", item_id: product.id), style:"text-decoration: none;", remote: true do %>
                    <button class='btn-minus'>-</button>
                  <% end %>
                  <input type='number' min='1' value='<%= cart[0]["quantity"] %>' style= 'border: 1px solid #d9d9d9; text-align: center;'>
                  <%= link_to edit_cart_path(action_edit: "plus", item_id: product.id), style:"text-decoration: none;", remote: true do %>
                    <button class='btn-plus'>+</button>
                  <% end %>
                </div>
              </td>
              <td class="position-relative text-center">
                <div class="cart-detail" style="width:100px"><%= number_with_delimiter(cart[0]["quantity"].to_i*discount(product).to_i) %> vnd</div>
              </td>
              <td class="position-relative" >
                <%= link_to edit_cart_path(action_edit: "delete", item_id: product.id), style:"text-decoration: none;", remote: true do %>
                  <i class="fa fa-trash cart-detail" aria-hidden="true"></i>
                <% end %>
              </td>
            </tr>
            <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="col-xl-3 mb-5">
    <table class="table table-borderless mb-0">
      <tbody>
        <tr>
          <td>Tổng giá sản phẩm</td>
          <% @total = 0%>
          <% session[:cart].each do |cart| %>
            <% product = Product.find(cart[0]["id"]) %>
            <% @total += cart[0]["quantity"].to_i*discount(product).to_i %>
          <% end %>
          <td class="text-right">
            <%= number_with_delimiter(@total) %> vnd
          </td>
        </tr>
        <tr>
          <td>
            <h5>Giao hàng giá rẻ</h5>
          </td>
          <td class="text-right"><%= number_with_delimiter(30000) %> vnd</td>
        </tr>
        <tr>
          <td>
            <h5>Tổng thanh toán</h5>
          </td>
          <td class="text-right"><%= number_with_delimiter(@total + 30000) %> vnd</td>
          <% session[:total] = @total + 30000 %>
        </tr>
      </tbody>
    </table>
    <button>
      <%= link_to 'Thanh toán', checkout_path, class:"btn btn-add2cart" %>
    </button>
  </div>
</div>

app/views/shopping/_pagination.html.erb
<% link = pagy_link_proc(pagy) %>
<nav aria-label="pager" class="table-pagination" role="navigation">
  <ul class="pagination">
    <% if pagy.prev %>
      <li class="page-item">
        <%== link.call(pagy.prev, '<span class="icon-ic-arrow-left page-link__previous" aria-hidden="true">Previous</span>', 'aria-label="previous" class="page-link"') %>
      </li>
    <% else %>
      <li class="page-item disabled">
        <%==link.call(1, '<span class="icon-ic-arrow-left page-link__previous" aria-hidden="true">Previous</span>', 'class="page-link"') %>
      </li>
    <% end %>
    <% pagy.series.each do |item| %>
      <% if item.is_a?(Integer) %>
        <li class="page-item">
          <%== link.call(item, item, 'class=page-link') %>
        </li>
      <% elsif item.is_a?(String) %>
        <li class="page-item active">
          <%= link_to(item, "javascript:void(0)", class: "page-link") %>
        </li>
      <% elsif item == :gap %>
        <li class="page-item disabled">
          <%== link_to("...", "javascript:void(0)", class: "page-link") %>
        </li>
      <% end %>
    <% end %>
    <% if pagy.next %>
      <li class="page-item">
        <%== link.call(pagy.next, '<span class="icon-ic-arrow-right page-link__next" aria-hidden="true">Next</span>', 'aria-label="next" class="page-link"') %>
      </li>
    <% else %>
      <li class="page-item disabled">
        <%== link.call(pagy.last, '<span class="icon-ic-arrow-right page-link__next" aria-hidden="true">Next</span>', 'class="page-link"') %>
      </li>
    <% end %>
  </ul>
</nav>

app/views/shopping/_products.html.erb
<div class="col-md-9 menu-right">
  <div class="title">
    <h2 class="border-bottom"><%= t('.vietnamese_specialty') %></h2>
  </div>
  <div class="row all-products">
    <% @products.each do |pr|%>
      <div class="col-md-4 mb-30px">
        <div class="card text-center my-2 px-0 d-flex align-items-center h-100">
          <%= link_to "product_detail/#{pr.id}", class: 'w-100 p-10px' do %>
            <%= cl_image_tag pr.photos.first.photo_url, class: 'w-100'%>
          <% end %>
          <div class="mt-auto">
            <%= link_to pr.name, "product_detail/#{pr.id}", class: 'card-name font-size-20px font-weight-700 mt-20px'%>
            <p style="color: #ffc107; font-weight: 700; font-size: 18px;">Đặc sản <%= City.find(pr.city_id).name %></p>
            <div class="price-css" style="text-decoration: line-through;"><span><%= number_with_delimiter(pr.price) %> vnd</span></div>
            <span class="dis-price"><%= number_with_delimiter(discount(pr))%> vnd</span>
            <div class="add-to-cart">
              <button class='btn-minus' onclick="decrement(<%= pr.id %>)">-</button>
              <input id='demoInput<%= pr.id %>' type='number' min='1' max='100' value='1' style= 'border: 1px solid #d9d9d9; text-align: center;'>
              <button class='btn-plus' onclick="increment(<%= pr.id %>)">+</button>
            </div>
            <div class="view my-10px">
              <button class="btn btn-add2cart" onclick="addToCart(<%= pr.id %>)" data-bs-toggle="modal" data-bs-target="#addToCartModal">Thêm vào giỏ hàng</button>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <% if @products.size > 0 %>
    <div class="pagination mt-3">
      <%= render 'pagination', pagy: @pagy %>
    </div>
  <% else %>
    Chưa có sản phẩm nào. ^^
  <% end %>
</div>

app/views/shopping/_sort.html.erb
<div class="col-md-9 menu-right">
  <div class="title">
    <h2 class="border-bottom">Đặc sản Việt Nam</h2>
  </div>
  <div class="row all-products">
    <% @products.each do |pr|%>
      <div class="col-md-4 mb-30px">
        <div class="card text-center my-2 px-0 d-flex align-items-center h-100">
          <%= link_to "product_detail/#{pr.id}", class: 'w-100 p-10px' do %>
            <%= cl_image_tag pr.photos.first.photo_url, class: 'w-100'%>
          <% end %>
          <div class="mt-auto">
            <%= link_to pr.name, "product_detail/#{pr.id}", class: 'card-name font-size-20px font-weight-700 mt-20px'%>
            <div class="price-css" style="text-decoration: line-through;"><span><%= number_with_delimiter(pr.price) %> vnd</span></div>
            <span class="dis-price"><%= number_with_delimiter(discount(pr))%> vnd</span>
            <div class="add-to-cart">
              <button class='btn-minus' onclick="decrement(<%= pr.id %>)">-</button>
              <input id='demoInput<%= pr.id %>' type='number' min='1' max='100' value='1' style= 'border: 1px solid #d9d9d9; text-align: center;'>
              <button class='btn-plus' onclick="increment(<%= pr.id %>)">+</button>
            </div>
            <div class="view my-10px">
              <%= link_to shopping_path, method: :post do %>
                <button type="submit" class="btn btn-add2cart" onclick="addToCart(<%= pr.id %>)" data-bs-toggle="modal" data-bs-target="#addToCartModal">Thêm vào giỏ hàng</button>
              <% end%>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="pagination mt-3">
    <%= render 'pagination', pagy: @pagy %>
  </div>
</div>

app/views/shopping/edit_cart.js.erb
edit_cart = $("#cart");
if (typeof(edit_cart) != 'undefined' && edit_cart != null)
{
  edit_cart.replaceWith("<%=j render 'edit_cart' %>");
}

app/views/shopping/index.html.erb
<section class="path">
  <div class="container">
    <div class="row">
      <div class="col-md-9">
      </div>
      <div class="col-md-3">
        <!-- Example single danger button -->
        <div class="btn-group" style="float: right">
          <button type="button" class="btn btn-warning dropdown-toggle px-3" data-toggle="dropdown">Phân loại</button>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="#">Giá từ thấp đến cao</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Giá từ cap đến thấp</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Đặc sản yêu thích</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- end section path -->
<!-- section shop-menu -->
<section class="shop-menu">
  <div class="container">
    <div class="row">
      <div class="col-md-3 menu-left">
        <div class="type-of-fruits">
          <h2 class="titlte border-bottom"><%= t('.area') %></h2>
          <div class="list-item p-4">
            <ul>
              <% Region.all.each do |region| %>
                <li>
                  <%= link_to region.name, shopping_path(region: region.id) %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
      <%= render 'products' %>
    </div>
  </div>
</section>
<!-- end section shop menu -->
<!-- Modal -->
<div class="modal fade" id="addToCartModal" tabindex="-1" aria-labelledby="addToCartModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="addToCartModalLabel">Thông báo</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Thêm vào giỏ hàng thành công
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<script>
  function increment(id) {
     document.getElementById('demoInput' + id).stepUp();
  }
  function decrement(id) {
     document.getElementById('demoInput' + id).stepDown();
  }
  function addToCart(id) {
    var quantity = $('#demoInput' + id).val()
    $.ajax({
      type: "POST",
      url: '/shopping',
      data: {
        item_id:  id,
        quantity: quantity
      },
      dataType: 'script'
    });
  }
</script>

app/views/shopping/index.js.erb
products = $(".menu-right");
if (typeof(products) != 'undefined' && products != null)
{
  products.replaceWith("<%=j render 'products' %>");
}