config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root 'home#index'
    get 'shopping',           to: 'shopping#index'
    get 'edit_cart',          to: 'shopping#edit_cart'
    get 'term',               to: 'home#term'
    get 'about_us',           to: 'home#about_us'
    get 'contact',            to: 'home#contact'
    get 'my_acc',             to: 'home#my_acc'
    get 'cart',               to: 'home#cart'
    get 'checkout',           to: 'home#checkout'
    get 'product_detail/:id', to: 'home#product_detail'


    get 'payment',            to: 'payment#index'
    post 'payment',           to: 'payment#create'


    get 'sitemap',            to: 'sitemap#index'

    post 'shopping',          to: 'shopping#cart'
    post 'order',             to: 'home#order'
    post 'information',       to: 'home#information'


    devise_for :customers, controllers: {
      sessions: 'customers/auths/sessions',
      registrations: 'customers/auths/registrations',
      confirmations: 'customers/auths/confirmations',
      passwords: 'customers/auths/passwords'
    }

    devise_for :administrators, controllers: {
      sessions: 'admins/auths/sessions',
      passwords: 'admins/auths/passwords'
    }
  end

  scope "(:locale)", locale: /en/, defaults: {locale: "en"} do
    devise_scope :administrator do
      get 'admin', to: 'admins/auths/sessions#new'
      get 'customers_export', to: 'admins/exports#customers_export'
      get 'admins_export', to: 'admins/exports#admins_export'
      get 'orders_export', to: 'admins/exports#orders_export'
    end

    namespace :admins, path: 'admin' do
      resources :admins
      resources :customers
      resources :products
      resources :photos
      resources :orders
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include Pagy::Backend
  layout 'application'
  def index
  end

  def term
  end

  def about_us
  end

  def contact
  end

  def product_detail
  end

  def my_acc
    authenticate_customer!
    @pagy, @orders = pagy(Order.all.where(customer_id: current_customer), items: 5, link_extra: 'data-remote="true"')
  end

  def information
    if current_customer.valid_password?(params[:password])
      current_customer.update(
        real_name: params[:name],
        phone:      params[:phone],
        city:       params[:city],
        district:   params[:district],
        address:    params[:address],
      )
      flash[:success] = "Cập nhật thành công!"
    else
      flash[:error] = "Mật khẩu không chính xác! Vui lòng thử lại!"
    end
    redirect_to my_acc_path
  end

  def cart
  end

  def checkout
    authenticate_customer!
    if session[:cart].nil? || session[:total] == 30000
      redirect_to cart_path
    else
      if params[:success]
        session.delete(:cart)
      end
    end
  end

  def order
    if params[:city].empty? || params[:real_name].empty? || params[:phone].empty? || params[:district].empty? || params[:address].empty?
      flash[:error] = "Hãy điền đẩy đủ thông tin trước khi đặt hàng!"
      redirect_to checkout_path
    else
      current_customer.update(
        real_name:      params[:real_name],
        phone:          params[:phone],
        city:           params[:city],
        district:       params[:district],
        address:        params[:address]
      )
      @order = Order.create(
        customer_id:    current_customer.id,
        total:          params[:total],
        detail:         params[:detail],
        payment_method: params[:payment_method],
        city:           params[:city],
        district:       params[:district],
        address:        params[:address]
      )
      if params[:payment_method] == 'paypal'
        redirect_to payment_path(order_id: @order.id)
      else
        OrderMailer.with(order: @order, customer: current_customer).order_email.deliver_later
        flash[:success] = "Đặt hàng thành công. Vui lòng kiểm tra email để xem thông tin đơn hàng!"
        redirect_to checkout_path(success: true)
      end
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
  include Pagy::Frontend
end

app/views/home/_order.html.erb
<div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
  <div class="card-body">
    <div class="title border-bottom">
      <h1>Các đơn hàng</h1>
    </div>
    <% if @orders.present? %>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Ngày</th>
            <th scope="col">Tổng</th>
            <th scope="col">Chi tiết</th>
            <th scope="col">Trạng thái</th>
          </tr>
        </thead>
        <tbody>
          <% @orders.each do |order| %>
            <tr>
              <td><%= order.created_at.strftime("%d %b %Y") %></td>
              <td><%= number_with_delimiter(order.total) %> vnd</td>
              <td><%= order.detail %></td>
              <td>
                <% if order.status == 'pending' %>
                  Đang xử lý
                <% elsif order.status == 'shipping' %>
                  Đang vận chuyển
                <% else %>
                  Hoàn tất
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <p>Bạn chưa có đơn hàng nào. ^^</p>
    <% end %>
    <%= render 'shopping/pagination', pagy: @pagy %>
  </div>
</div>

app/views/home/about_us.html.erb
<!-- section about us -->
<section class="about-us">
  <div class="container p-5">
    <div class="title text-center">
      <h1>Sơ lược</h1>
    </div>
    <div class="content">
      <div class="row">
        <div class="col-12">
          <p>Từ năm 2015 tới nay nhu cầu sử dụng hàng đặc sản ngày càng được quan tâm và sử dụng nhiều, được sử dụng như 1 sản phẩm hàng ngày thay vì sử dụng như một món quà như ngày xưa.</p>
        </div>
        <div class="col-12">
          <p>Tuy nhiên sau thời gian làm việc, nhận ra thị trường hàng đặc sản còn khó tiếp cận, chưa có nhiều doanh nghiệp hoặc công ty tổ chức hỗ trợ người dân phát triển mặt hàng lợi thế tại địa phương đó và việc đảm bảo chất lượng cho hàng đặc sản chưa đáp ứng được nhu cầu của khách hàng.</p>
        </div>
        <div class="col-12">
          <p>DacSanVietNam được thành lập bởi nhóm các sinh viên Bách Khoa - Khoa Khoa Học Và Kỹ Thuật Máy Tính vào năm 2022 tại TP. Hồ Chí Minh. Hiện nay, DacSanVietNam là thương hiệu chuyên cung cấp sản phẩm đặc sản chế biến chất lượng cao, an toàn, tin cậy, phải chăng, đẹp mắt, hài lòng từ khắp cả 63 tỉnh thành trên cả nước.</p>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- end section about us -->
<!-- section why choose us -->
<section class="why-choose-us py-5">
  <div class="container text-center">
    <div class="title my-5">
      <h1>Tại sao lại chọn chúng tôi</h1>
    </div>
    <div class="row">
      <div class="col-md-6">
        <div class="row">
          <div class="col-md-6">
            <div class="icon"><i class="fas fa-child"></i></div>
            <div class="title">Sứ mệnh</div>
            <p class="subtitle">DacSanVietNam luôn làm việc chăm chỉ mỗi ngày để tạo ra những sản phẩm đặc sản uy tín, chất lượng cao, tốt cho sức khoẻ, hậu mãi hài lòng để cung cấp cho khách hàng.</p>
            <p>Chúng tôi luôn mang trong mình khát vọng có thể giới thiệu cho toàn Thế Giới những sản phẩm tốt như vậy từ quê hương mình.</p>
          </div>
          <div class="col-md-6">
            <div class="icon"><i class="fas fa-heartbeat"></i></div>
            <div class="title">Niềm tin</div>
            <p class="subtitle">DacSanVietNam mong muốn đưa đặc sản trở thành một phần có nghĩa và hợp lý trong cuộc sống bận rộn hàng ngày. Chúng tôi tin rằng DacSanVietNam luôn  mang trong mình giá trị vô cùng to lớn.</p>
            <p>Tuy vậy, khai thác được giá trị đó là một thách thức rất lớn. Chúng ta cần phải làm việc chăm chỉ hơn nữa, sáng tạo hơn nữa để có thể đưa nông sản trở thành một phần có nghĩa và hợp lý với cuộc sống hàng ngày đầy bận rộn của con người.</p>
          </div>
        </div>
        <%# <div class="row my-5">
          <div class="col-md-6">
            <div class="icon"><i class="far fa-lemon"></i></div>
            <div class="title">Rau củ</div>
            <div class="subtitle">Entropy thông tin là một khái niệm mở rộng của entropy trong nhiệt động lực học và cơ học thống kê sang cho lý thuyết thông tin.</div>
          </div>
          <div class="col-md-6">
            <div class="icon"><i class="fas fa-seedling"></i></div>
            <div class="title">Trái cây</div>
            <div class="subtitle">Entropy thông tin là một khái niệm mở rộng của entropy trong nhiệt động lực học và cơ học thống kê sang cho lý thuyết thông tin.</div>
          </div>
        </div> %>
      </div>
      <div class="col-md-6">
        <div class="why-choose-us-img"></div>
      </div>
    </div>
  </div>
</section>
<!-- end section why choose us -->

app/views/home/cart.html.erb
<section class="container">
  <% if session[:cart].nil? %>
    <h2 style="height: 500px">Giỏ hàng trống!</h2>
  <% else %>
    <%= render 'shopping/edit_cart' %>
  <% end %>
</section>

app/views/home/checkout.html.erb
<section class="container">
  <% if flash[:success].present? %>
    <p class= "alert" style="color:green">
      <%= flash[:success] %>
    </p>
  <% else %>
    <%= form_with url: order_path, method: :post do |f| %>
      <div class="row mb-5">
        <div class="col-12 col-xl-8">
          <h5 class="font-weight-bold">Chi tiết thanh toán</h5>
          <% if flash[:error].present? %>
            <p class= "alert color-red">
              <%= flash[:error] %>
            </p>
          <% end %>
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <label>Họ và tên</label>
                <%= f.text_field  :real_name, class: "form-control", value: current_customer.real_name %>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <label>Số điện thoại</label>
                <%= f.text_field  :phone, class: "form-control", type:"number", value: current_customer.phone %>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <label>Email</label>
                <input disabled type="text" class="form-control" value="<%= current_customer.email %>">
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <label>Tổng hóa đơn</label>
                <input disabled type="text" class="form-control" value="<%= number_with_delimiter(session[:total]) %> vnd">
                <%= f.text_field  :total, class: "form-control d-none", value: session[:total] %>
              </div>
            </div>
            <div class="col-md-12 mt-10px">
              <div class="form-group">
                <label>Danh sách sản phẩm</label>
                <% detail = ""  %>
                <% session[:cart].each do |cart| %>
                  <% if cart[0]["quantity"]!= 0 %>
                    <% detail += '(' + Product.find(cart[0]["id"]).name + " x" + cart[0]["quantity"].to_s + ') ' %>
                    <p style="color: green"><%= Product.find(cart[0]["id"]).name + " x" + cart[0]["quantity"].to_s %></p>
                  <% end %>
                <% end %>
                <%= f.text_field  :detail, class: "form-control d-none", value: detail %>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <label>Tỉnh / Thành phố </label>
                <%= f.text_field  :city, class: "form-control", value: current_customer.city %>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <label>Quận / Huyện</label>
                <%= f.text_field  :district, class: "form-control", value: current_customer.district %>
              </div>
            </div>
            <div class="col-md-12">
              <div class="form-group">
                <label>Địa chỉ cụ thể</label>
                <%= f.text_field  :address, class: "form-control", value: current_customer.address %>
              </div>
            </div>
          </div>
          <%= link_to cart_path do %>
            <button class= "btn btn-add2cart mt-20px">Quay lại giỏ hàng</button>
          <% end %>
        </div>
        <div class="col-12 col-xl-4">
          <div class="cart_totals">
            <div class="table-responsive">
              <h5 class="font-weight-bold">Phương thức thanh toán</h5>
              <div class="ul-css m-0">
                <ul class="m-0 ml-3">
                  <div class="mb-20px">
                    <%= f.radio_button :payment_method, "cod", checked: true %>
                    <label for="payment_method_bacs"> COD (Thanh toán khi nhận hàng) </label>
                  </div>
                  <div class="mb-20px">
                    <%= f.radio_button :payment_method, "paypal", checked: params[:paypal].present? ? true : false  %>
                    <label for="payment_method_bacs"> Paypal (Stripe) </label>
                  </div>
                  <%= f.radio_button :payment_method, "transfer" %>
                  <label for="payment_method_bacs"> Chuyển khoản ngân hàng </label>
                  <div>
                    <p>Thực hiện thanh toán của bạn trực tiếp vào tài khoản ngân hàng của chúng tôi. Vui lòng sử dụng ID đơn đặt hàng của bạn làm tham chiếu thanh toán. Đơn đặt hàng của bạn sẽ không được chuyển cho đến khi tiền đã gửi
                      trong tài khoản của chúng tôi.</p>
                  </div>
                  <%= f.submit "Đặt hàng", class: "btn btn-add2cart" %>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</section>

app/views/home/contact.html.erb
<!-- section map -->
<section class="map">
  <div class="container-fluid">
    <iframe class="location w-100" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3595.5562446044946!2d106.65855386847525!3d10.773437489394041!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31752ec3c161a3fb%3A0xef77cd47a1cc691e!2zVHLGsOG7nW5nIMSQ4bqhaSBo4buNYyBCw6FjaCBraG9hIC0gxJDhuqFpIGjhu41jIFF14buRYyBnaWEgVFAuSENN!5e0!3m2!1svi!2s!4v1619931859137!5m2!1svi!2s"
          style="border:0; height: 100vh" allowfullscreen="" loading="lazy"></iframe>
  </div>
</section>
<!-- end section map -->
<!-- section infor -->
<section class="infor my-5">
  <div class="container">
    <div class="row">
      <div class="col-md-4 text-center">
        <div class="icon"><i class="fas fa-map-marker-alt"></i></div>
        <div class="content">268 Lý Thường Kiệt P14 quận 10 tpHCM</div>
      </div>
      <div class="col-md-4 text-center">
        <p class="phone"><i class="fas fa-phone mr-20px"></i><%= t('.telephone') %>: +84 1234568789</p>
        <a href="mailto:dacsanvietnamheroku@gmail.com" style= "text-decoration: none;">
          <p class="email"><i class="fas fa-envelope mr-20px"></i>Email: <span>dacsanvietnamheroku@gmail.com</span></p>
        </a>
      </div>
      <div class="col-md-4 text-center">
        <div class="icon"><i class="far fa-clock"></i></div>
        <div class="content">
          <div class="week-day">Week Days : 8:00 – 22:00</div>
          <div class="sunday">Sunday : Close</div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- end section infor -->
<!-- section leave message -->
<section class="leave-message">
  <div class="container text-center">
    <div class="title">Để lại lời nhắn</div>
    <div class="subtitle mt-2 mb-5">Nhân viên chúng tôi sẽ gọi lại và trả lời câu hỏi sớm nhất cho bạn</div>
    <form>
      <div class="row">
        <div class="col-md-6">
          <input type="text" class="input-message-name form-control" id="name" name="name" placeholder="Name">
        </div>
        <div class="col-md-6">
          <input class="input-message-email form-control" type="text" name="email" placeholder="Email">
        </div>
      </div>
      <textarea class="textarea-message-content form-control my-3" name="content" cols="30" rows="10" placeholder="Your message"></textarea>
      <div class="btn btn-warning py-2 px-4 mb-5">Submit</div>
    </form>
  </div>
</section>
<!-- end section leave message  -->

app/views/home/index.html.erb
  <!-- section baner -->
<section class="baner">
  <div id="carouselBaner" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselBaner" data-slide-to="0" class="active"></li>
      <li data-target="#carouselBaner" data-slide-to="1"></li>
      <li data-target="#carouselBaner" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <%= image_tag 'bg3.jpg', class:"d-block w-100", style: 'object-fit: cover; height: 900px', alt: "First slide" %>
      </div>
      <div class="carousel-item">
        <%= image_tag 'bg4.jpg', class:"d-block w-100", style: 'object-fit: cover; height: 900px', alt: "Second slide" %>
      </div>
      <div class="carousel-item">
        <%= image_tag 'bg2.jpg', class:"d-block w-100", style: 'object-fit: cover; height: 900px', alt: "Third slide" %>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselBaner" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselBaner" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</section>
<!-- end section baner -->
<!-- section trusted farms -->
<section class="trusted-farms py-5">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <%= image_tag 'antoan.jpg' %>
      </div>
      <div class="col-md-6">
        <div class="title">
          <h1><%= t('.the_most_reliable_information_for_you') %></h1>
        </div>
        <ul class="list-farms my-3">
          <li>
            <div class="icon"></div>
            <div class="list">
              <div class="list-title text-danger">An toàn</div>
              <div class="list-subtitle">Những thực phẩm được kiểm định nghiêm ngặt, an toàn vệ sinh thực phẩm.
              </div>
            </div>
          </li>
          <li>
            <div class="icon"></div>
            <div class="list">
              <div class="list-title text-danger">100% Thức ăn ngon</div>
              <div class="list-subtitle">Chúng tôi tìm kiếm và chọn lọc những đặc sản ngon nhất trên mọi miền tổ quốc.
              </div>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
</section>
<!-- end section trusted farms -->
<!-- section Service -->
<section class="service area-between">
  <div class="contain text-center">
    <h1 class="title"><%= t('.favorite_specialties') %></h1>
    <div class="subtitle d-flex justify-content-center">
      <p><%= t('.favorite_des') %></p>
    </div>
    <div class="row d-flex justify-content-center">
      <% Product.limit(6).order("RANDOM()").each do |pr| %>
        <div class="col-md-3 d-flex justify-content-center p-0 m-20px" style="min-height: 400px;">
          <div class="card d-flex justify-content-end my-4 w-100 h-100">
            <%= image_tag pr.photos.first.photo_url, class: 'mb-auto' %>
            <h3 class="card-title mt-20px"><%= pr.name %></h3>
            <p class="description">
              <% if pr.description.size > 100 %>
                <%= pr.description[0..100] %>...
              <% else %>
                <%= pr.description[0..100] %>
              <% end %>
            </p>
            <%= link_to t('.read_more'), "/product_detail/#{pr.id}", class: 'btn btn-outline-success' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>
<!-- end section Service -->
<!-- section product -->
<section class="product area-between">
  <div class="contain text-center">
    <h1 class="title"><%= t('.product') %></h1>
    <div class="subtitle d-flex justify-content-center">
      <p><%= t('.product_des') %></p>
    </div>
    <div class="row d-flex justify-content-center">
      <% Product.limit(4).order("RANDOM()").each do |pr| %>
        <div class="col-md-3 mb-30px">
          <div class="card text-center my-2 px-0 d-flex align-items-center h-100">
            <%= link_to "product_detail/#{pr.id}", class: 'w-100 p-10px' do %>
              <%= cl_image_tag pr.photos.first.photo_url, class: 'w-100'%>
            <% end %>
            <div class="mt-auto">
              <%= link_to pr.name, "product_detail/#{pr.id}", class: 'card-name font-size-20px font-weight-700 mt-20px'%>
              <p style="color: #ffc107; font-weight: 700; font-size: 18px;"><%= t('.specialty') %> <%= City.find(pr.city_id).name %></p>
              <div class="price-css" style="text-decoration: line-through;"><span><%= number_with_delimiter(pr.price) %> vnd</span></div>
              <span class="dis-price"><%= number_with_delimiter(discount(pr))%> vnd</span>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <%= link_to shopping_path do %>
      <div class="btn btn-outline-danger mt-5 py-2 px-4"><%= t('.view_more') %></div>
    <% end %>
  </div>
</section>
<!-- end section product -->
<!-- section contact -->
<section class="contact area-between">
  <div class="contain text-center">
    <h1 class="title"><%= t('.welcome') %></h1>
    <p class="subtitle"><%= t('.welcome_des') %></p>
    <%= link_to contact_path do %>
      <div class="btn btn-dark mt-5 py-2 px-4 contact-btn">
        <%= t('.contact_us') %>
      </div>
    <% end %>
  </div>
</section>
<!-- end section contact -->

app/views/home/my_acc.html.erb
<!-- section more infor-->
<section class="more-infor my-5">
  <div class="container">
    <div id="row">
      <div class="col-md-12">
        <% flash.each do |key, value| %>
          <% if !value.nil? %>
            <div class="alert" style="color: <%= key == 'error' ? 'red' : 'green' %>">
              <%= value %>
            </div>
          <% end %>
        <% end %>
        <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
          <div class="card-body">
            <div class="title border-bottom">
              <h1>Các đơn hàng</h1>
            </div>
            <% if @orders.present? %>
              <table class="table">
                <thead>
                  <tr>
                    <th scope="col">Ngày</th>
                    <th scope="col">Tổng</th>
                    <th scope="col">Chi tiết</th>
                    <th scope="col">Trạng thái</th>
                  </tr>
                </thead>
                <tbody>
                  <% @orders.each do |order| %>
                    <tr>
                      <td><%= order.created_at.strftime("%d %b %Y") %></td>
                      <td><%= number_with_delimiter(order.total) %> vnd</td>
                      <td><%= order.detail %></td>
                      <td>
                        <% if order.status == 'pending' %>
                          Đang xử lý
                        <% elsif order.status == 'shipping' %>
                          Đang vận chuyển
                        <% elsif order.status == 'paid' %>
                          Đã thanh toán (Đang xử lý)
                        <% else %>
                          Hoàn tất
                        <% end %>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            <% else %>
              <p>Bạn chưa có đơn hàng nào. ^^</p>
            <% end %>
            <%= render 'shopping/pagination', pagy: @pagy %>
          </div>
        </div>
        <div id="collapseTwo" class="collapse mx-auto" style="width: 800px" aria-labelledby="headingTwo" data-parent="#accordion">
          <div class="card-body">
            <%= form_with url: information_path, method: :post, class:'card p-5 m-5  bg-light' do |f| %>
              <div class="title text-center">
                <h1>Thông tin tài khoản</h1>
              </div>
              <div class="form-group">
                <label>Họ và tên</label>
                <%= f.text_field :name, class: 'form-control', value: current_customer.real_name, placeholder:"Họ và tên" %>
              </div>
              <div class="form-group">
                <label>Số điện thoại</label>
                <%= f.text_field :phone, class: 'form-control', value: current_customer.phone, placeholder:"Số điện thoại" %>
              </div>
              <div class="form-group">
                <label>Tỉnh/ Thành phố</label>
                <%= f.text_field :city, class: 'form-control', value: current_customer.city, placeholder:"Tỉnh/ Thành phố" %>
              </div>
              <div class="form-group">
                <label>Quận/ Huyện</label>
                <%= f.text_field :district, class: 'form-control', value: current_customer.district, placeholder:"Quận/ Huyện" %>
              </div>
              <div class="form-group">
                <label>Địa chỉ</label>
                <%= f.text_field :address, class: 'form-control', value: current_customer.address, placeholder:"Địa chỉ cụ thể" %>
              </div>
              <div class="form-group">
                <label>Mật khẩu</label>
                <%= f.password_field :password, class: 'form-control', placeholder:"Mật khẩu" %>
              </div>
              <button type="submit" class="btn btn-warning mt-2">Cập nhật</button>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-md-12">
        <div id="accordion">
          <div class="card">
            <div class="card-header text-center" id="headingTwo">
              <h5 class="mb-0">
                <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                  Thông tin tài khoản
                </button>
              </h5>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- end section more infor -->

app/views/home/my_acc.js.erb
order = $("#collapseOne");
if (typeof(order) != 'undefined' && order != null)
{
  order.replaceWith("<%=j render 'order' %>");
}