config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root 'home#index'
    get 'shopping',           to: 'shopping#index'
    get 'edit_cart',          to: 'shopping#edit_cart'
    get 'term',               to: 'home#term'
    get 'about_us',           to: 'home#about_us'
    get 'contact',            to: 'home#contact'
    get 'my_acc',             to: 'home#my_acc'
    get 'cart',               to: 'home#cart'
    get 'checkout',           to: 'home#checkout'
    get 'product_detail/:id', to: 'home#product_detail'


    get 'payment',            to: 'payment#index'
    post 'payment',           to: 'payment#create'


    get 'sitemap',            to: 'sitemap#index'

    post 'shopping',          to: 'shopping#cart'
    post 'order',             to: 'home#order'
    post 'information',       to: 'home#information'


    devise_for :customers, controllers: {
      sessions: 'customers/auths/sessions',
      registrations: 'customers/auths/registrations',
      confirmations: 'customers/auths/confirmations',
      passwords: 'customers/auths/passwords'
    }

    devise_for :administrators, controllers: {
      sessions: 'admins/auths/sessions',
      passwords: 'admins/auths/passwords'
    }
  end

  scope "(:locale)", locale: /en/, defaults: {locale: "en"} do
    devise_scope :administrator do
      get 'admin', to: 'admins/auths/sessions#new'
      get 'customers_export', to: 'admins/exports#customers_export'
      get 'admins_export', to: 'admins/exports#admins_export'
      get 'orders_export', to: 'admins/exports#orders_export'
    end

    namespace :admins, path: 'admin' do
      resources :admins
      resources :customers
      resources :products
      resources :photos
      resources :orders
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/admins/admins/_form_create.html.erb
<%= simple_form_for @admin, url: url, method: method do |f| %>
  <div class="form-inputs mb-10px form-cms row">
    <div class="form-cms-input col-xxl-3">
      <label>Email *</label>
      <%= f.input :email,
        required: true, label: false,
        input_html: { class: "form-control" } %>
    </div>
    <div class="form-cms-input col-xxl-3">
      <label>Password *</label>
      <%= f.input :password,
        required: true, label: false,
        input_html: { class: "form-control" } %>
    </div>
  </div>
<div class="form-actions d-none">
  <%= f.button :submit, "Create", class: "", id: "button-submit" %>
</div>
<% end %>

app/views/admins/admins/_form_update.html.erb
<%= simple_form_for @admin, url: url, method: method do |f| %>
  <div class="form-inputs mb-10px form-cms row">
    <div class="form-cms-input col-xxl-3">
      <label>Email *</label>
      <%= f.input :email,
        required: true, label: false,
        input_html: { class: "form-control" } %>
    </div>
    <div class="form-cms-input col-xxl-3">
      <label>Password *</label>
      <%= f.input :password,
        required: true, label: false,
        input_html: { class: "form-control" } %>
    </div>
  </div>
<div class="form-actions d-none">
  <%= f.button :submit, "Save", class: "", id: "button-submit" %>
</div>
<% end %>

app/views/admins/admins/_sort.html.erb
<div class="card-body body-admin p-0">
  <div class="table-responsive">
    <table class="table table-borderless">
      <thead class="bg-muted">
        <tr>
          <th scope="col" class="pl-38px">UID</th>
          <% if @class_sort%>
            <% if @class_sort == "username"%>
              <th scope="col">
                Username
                <%= link_to admins_admins_path(sort_contra: "username"), class:'sort-contra', remote: true do %>
                  <%= image_tag 'sort_contra.svg', class:"pb-5px"%>
                <% end %>
              </th>
              <th scope="col">
                Email
                <%= link_to admins_admins_path(sort: "email"), class: "email_sort", remote: true do %>
                  <%= image_tag 'sort_icon.svg', class:"pb-5px"%>
                <% end %>
              </th>
            <% else%>
              <th scope="col">
                Username
                <%= link_to admins_admins_path(sort: "username"), class: "username_sort", remote: true do %>
                  <%= image_tag 'sort_icon.svg', class:"pb-5px"%>
                <% end %>
              </th>
              <th scope="col">
                Email
                <%= link_to admins_admins_path(sort_contra: "email"), class:'sort-contra', remote: true do %>
                  <%= image_tag 'sort_contra.svg', class:"pb-5px"%>
                <% end %>
              </th>
            <% end%>
          <% else%>
            <th scope="col">
              Username
              <%= link_to admins_admins_path(sort: "username"), class: "username_sort", remote: true do %>
                <%= image_tag 'sort_icon.svg', class:"pb-5px"%>
              <% end %>
            </th>
            <th scope="col">
              Email
              <%= link_to admins_admins_path(sort: "email"), class: "email_sort", remote: true do %>
                <%= image_tag 'sort_icon.svg', class:"pb-5px"%>
              <% end %>
            </th>
          <% end%>
          <th scope="col">Created on</th>
          <th scope="col" class="pr-200px">Status</th>
          <th scope="col" class="width-100px pr-172px"></th>
        </tr>
      </thead>
      <tbody>
        <% i = 1 %>
        <% @admins.each do |admin| %>
          <tr style = "background-color: <%= i % 2 == 0? '#F9F9F9' : '' %> ">
            <% i += 1 %>
            <th scope="row" class="pl-38px"><%= 1000 + admin.id %></th>
            <td><%= admin.username %></td>
            <td><%= admin.email %></td>
            <td><%= admin.created_at.strftime("%d %b %Y") %></td>
            <td>
              <% if admin.status == 'available' %>
                <%= 'Active' %>
              <% else %>
                <%= 'Inactive' %>
              <% end %>
            </td>
            <td>
              <%= link_to edit_admins_admin_path(admin), class: 'admin-link' do %>
                <%= image_tag 'pencil_edit.svg'%>
              <% end %>
              <% unless current_administrator == admin %>
                <%= link_to admins_admin_path(admin), method: :DELETE, class: 'admin-link color-red' do %>
                <%= image_tag 'trash.svg'%>
                <% end %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <%== render partial: 'shared/pagination', locals: {pagy: @pagy} %>
</div>

app/views/admins/admins/edit.html.erb
<div class="card">
  <div class="card-header p-10px text-end">
    <button type="button" class="btn btn-yellow btn-save">Save</button>
  </div>
  <div class="admin-form-body">
    <%= render 'form_update', url: admins_admin_path, method: :PUT %>
  </div>
</div>
<script type="text/javascript">
  $('.btn-save').click(function(){
    $("#button-submit").click()
  })
</script>

app/views/admins/admins/index.html.erb
<div class="">
  <div class="card">
    <div class="card-header p-10px">
      <div class="d-flex" style="justify-content: space-between;">
        <div class="ml-28px">
          <%= link_to new_admins_admin_path,
              class: 'btn btn-create' do %>
              <%= image_tag "icon_add.png", style:"width:16px" %> Create
          <% end %>
          <%= link_to 'Export', admins_export_path(format: :csv), class: 'btn btn-create'%>
        </div>
        <div class="search-tab mr-96px">
          <i class="fas fa-search search-icon"></i>
          <%= form_tag(admins_admins_path, method: 'get') do %>
            <%= text_field_tag(:search, params[:search], class:"form-control search-bar mt-5px pl-25px", placeholder: "Search" ) %>
          <% end%>
        </div>
      </div>
    </div>
    <div class="card-body body-admin p-0">
      <div class="table-responsive">
        <table class="table table-borderless  table-admin">
          <thead class="bg-muted">
            <tr>
              <th scope="col" class="pl-38px">UID</th>
              <th scope="col">
                Email
                <%= link_to admins_admins_path(sort: "email"), class: "email_sort", remote: true do %>
                  <%= image_tag 'sort_icon.svg', class:"pb-5px"%>
                <% end %>
              </th>
              <th scope="col">Created on</th>
              <th scope="col" class="width-100px pr-172px"></th>
            </tr>
          </thead>
          <tbody>
            <% i = 1 %>
            <% @admins.each do |admin| %>
              <tr style = "background-color: <%= i % 2 == 0? '#F9F9F9' : '' %> ">
                <% i += 1 %>
                <th scope="row" class="pl-38px"><%= 1000 + admin.id %></th>
                <td><%= admin.email %></td>
                <td><%= admin.created_at.strftime("%d %b %Y") %></td>
                <td>
                  <% unless admin.email == 'datpmt@gmail.com' %>
                    <%= link_to edit_admins_admin_path(admin), class: 'admin-link' do %>
                      <%= image_tag 'pencil_edit.svg'%>
                    <% end %>
                    <% unless current_administrator == admin %>
                      <%= link_to admins_admin_path(admin), method: :DELETE, data: {confirm: "Are you sure?"}, class: 'admin-link color-red' do %>
                      <%= image_tag 'trash.svg'%>
                      <% end %>
                    <% end %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="paging">
        <%== render partial: 'shared/pagination', locals: {pagy: @pagy} %>
      </div>
    </div>
  </div>
</div>

app/views/admins/admins/index.js.erb
sort = $(".body-admin");
if (typeof(sort) != 'undefined' && sort != null)
{
  sort.html("<%=j render 'sort' %>");
}

app/views/admins/admins/new.html.erb
<div class="card">
  <div class="card-header p-10px text-end">
    <button type="button" class="btn btn-yellow btn-save">Create</button>
  </div>
  <div class="admin-form-body">
    <%= render 'form_create', url: admins_admins_path, method: :POST %>
  </div>
</div>
<script type="text/javascript">
  $('.btn-save').click(function(){
    $("#button-submit").click()
  })
</script>